site_name: Concorrências Presenciais Lei 12.232/2010 - Novo DC

theme:
  name: readthedocs

markdown_extensions:
  - md_in_html
  - admonition

nav:
  - Início: index.md
  - 1. Criar a contratação: 01-criar-contratacao.md
  - 2. Dados e inclusão de itens: 02-dados-e-inclusao-de-itens.md
  - 3. Configuração de itens, grupos e anexos: 03-configuracao-grupos-e-anexos.md
  - 4. Responsáveis e divulgação: 04-responsaveis-e-divulgacao.md
  - 5. Incluir e divulgar resultados: 05-resultados-da-licitacao.md
  - 🖨️ Versão Completa para Impressão: manual-completo.md

# Configuração dos estilos e scripts customizados
extra_css:
  - custom.css
  - css/extra.css

extra_javascript:
  - js/custom.js
  - js/font-size.js
